name: case_connectinno
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  lottie: ^3.2.0
  go_router: ^16.3.0
  shared_preferences: ^2.5.3
  email_validator: ^3.0.0
  firebase_core: ^4.2.0
  firebase_analytics: ^12.0.3
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_localizations:
    sdk: flutter
  loading_animation_widget: ^1.3.0
  google_fonts: ^6.3.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
